### ISSUE TITLE
Support for 'revert' commits

### ISSUE THREAD

**Issue by mkemlogic** [EmLogic/git-hooks#3]
Currently when you do git revert <sha> git wants you to write a commit message as if it was a new commit. We should support regular revert commit messages:
`Revert "fix(readme): add something..."`

**Comment by mcbemlogic** [comment]
Should revert commits only be allowed on branches or will it also be allowed on the main branch?

**Comment by mkemlogic** [comment]
Also on main branch because we might want to revert a commit that is already on main

**Comment by mcbemlogic** [comment]
Seems I have to fix the message template stuff too since Revert gets a special commit edit message file

**Comment by mcbemlogic** [comment]
@mkemlogic this is what the revert commit message editor looks like: 
```
Revert "chore(config): change default stages from commit to pre-commit"

This reverts commit 8fd9f0c5cde5132723adb2141fb67123e89c47e9.

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch mcb/support_revert_commits
# Changes to be committed:
#	modified:   .pre-commit-config.yaml
#	modified:   templates/pre-commit-config.yaml
```

Should we also have our template below, incase the user wants to make their own commit message on the revert commit?

**Comment by mkemlogic** [comment]
Yes, makes sense
